### ISSUE TITLE
Supporting safesearch off

### ISSUE THREAD

**Issue by mp3il** [tristantao/py-bing-search#15]
Hi,

I will try to send a pull request today with the ability to choose whether safesearch is on or off (can be on by default, as bing supports)

but would be useful to have control over this param.

**Comment by tristantao** [comment]
Great, feel free to send a pr whenever you get a chance.

**Comment by michaelholm-ce** [comment]
I would like to have this ability as well.  Thank you.

**Comment by michaelholm-ce** [comment]
Temporarily, I changed 
QUERYSTRING_TEMPLATE = '?Query={}&$top={}&$skip={}&$format={}'
to 
QUERYSTRING_TEMPLATE = "?Adult='Strict'&Query={}&$top={}&$skip={}&$format={}"

**Comment by tristantao** [comment]
Check README (updating now) for how to use the new custom params feature.
