### ISSUE TITLE
Can py_bing_search be used to get Bing Side Box?

### ISSUE THREAD

**Issue by ReedJessen** [tristantao/py-bing-search#22]
Hello,

I am working on a project where I need to get the data which is populating the Bing side search box which occasionally appears for search for things of high prominence. (See attached screen snip)

Does this library allow me to get the data object backing this sidebox?

![sidebox search](https://cloud.githubusercontent.com/assets/12887285/19055093/2dd89bfc-8977-11e6-825f-f1746ea8b453.JPG)

**Comment by tristantao** [comment]
Unfortunately it does not grab the search box.
