### ISSUE TITLE
Migration from BingSearchApi to Microsoft Cognitive

### ISSUE THREAD

**Issue by ranam008** [tristantao/py-bing-search#23]
Hi Tristantao,

Thank you so much for providing the wrapper which is helping us a lot. Wanted to know as Microsoft is migrating BingSearchApi to Microsoft Cognitive services, can we expect a new version of the wrapper code if so by when? Can you please look into it as most of my work depends on this wrapper and it would be a great help if you can fix this 

Regards

**Comment by tristantao** [comment]
Hi @ranam008,

I'm already looking into creating a separate package for the cognitive service. My goal is to get something stable out by Dec 1st (I believe Dec 15th is the EOL for this product).

I should have more info in by end of next week on the scope of the package.

**Comment by tristantao** [comment]
As an update, there is a unstable (but working) version for the new API here: https://github.com/tristantao/py-ms-cognitive

Currently only the general webpage search works. If you have any feedback on what feature you need etc, do leave them here.

**Comment by tristantao** [comment]
Th new package seems stable enough. Closing this now.
