### ISSUE TITLE
Search News

### ISSUE THREAD

**Issue by parangsaraf** [tristantao/py-bing-search#3]
Hi,

Can you give an example on how to search just news using this wrapper? 

Thanks

**Comment by evanmiltenburg** [comment]
You can't, except if you modify the QUERY_URL. See the Azure datamarket page for examples of how to modify the URL. The base is `https://api.datamarket.azure.com/Bing/Search/v1/News` and a simple query for 'Angela Merkel' looks like this: `https://api.datamarket.azure.com/Bing/Search/v1/News?Query=%27angela%20merkel%27`.

**Comment by tristantao** [comment]
Old thread, I know. But the new version will handle images, videos, as well as news (specifically via 8e3ed75b02418403385c2be3441ce4b0d8ce94bc) @parangsaraf
