### ISSUE TITLE
Handling of unicode characters

### ISSUE THREAD

**Issue by MaZZly** [tristantao/py-bing-search#9]
Doesn't seem to hande Unicode characters too well..

```python
# Fails
bing.search_all(u'óla', limit=50)
>>> UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 0: ordinal not in range(128)

# Works
bing.search_all(u'óla'.encode('utf-8'), limit=50)
>>> [results]
```

Would it be good to add the encoding built-in to the code?

My suggestion would be to add to `py_bing_search.py:37` a line:
```python
query = query.encode('utf-8')
```

However I suck when it comes to unicode and the like so this might bring errors for other strings?

**Comment by evanmiltenburg** [comment]
I made a Python 3 fork that takes care of this bug: https://github.com/evanmiltenburg/py-bing-search
    >>> result = bing.search("olá", limit=50, format='json')
    >>> result
    ([<py_bing_search.Result object at 0x105a6c310>, <py_bing_search.Result object at 0x105a6c390>, <py_bing_search.Result object at 0x105a6c410>, <py_bing_search.Result object at 0x105a6c490>, <py_bing_search.Result object at 0x105a6c510>, <py_bing_search.Result object at 0x105a6c590>, <py_bing_search.Result object at 0x105a6c610>, <py_bing_search.Result object at 0x105a6c690>, <py_bing_search.Result object at 0x105a6c710>, <py_bing_search.Result object at 0x105a6c790>, <py_bing_search.Result object at 0x105a6c810>, <py_bing_search.Result object at 0x105a6c890>, <py_bing_search.Result object at 0x105a6c910>, <py_bing_search.Result object at 0x105a6c990>, <py_bing_search.Result object at 0x105a6ca10>, <py_bing_search.Result object at 0x105a6ca90>, <py_bing_search.Result object at 0x105a6cb10>, <py_bing_search.Result object at 0x105a6cb90>, <py_bing_search.Result object at 0x105a6cc10>, <py_bing_search.Result object at 0x105a6cc90>, <py_bing_search.Result object at 0x105a6cd10>, <py_bing_search.Result object at 0x105a6cd90>, <py_bing_search.Result object at 0x105a6ce10>, <py_bing_search.Result object at 0x105a6ce90>, <py_bing_search.Result object at 0x105a6cf10>, <py_bing_search.Result object at 0x105a6cf90>, <py_bing_search.Result object at 0x105a71050>, <py_bing_search.Result object at 0x105a710d0>, <py_bing_search.Result object at 0x105a71150>, <py_bing_search.Result object at 0x105a711d0>, <py_bing_search.Result object at 0x105a71250>, <py_bing_search.Result object at 0x105a712d0>, <py_bing_search.Result object at 0x105a71350>, <py_bing_search.Result object at 0x105a713d0>, <py_bing_search.Result object at 0x105a71450>, <py_bing_search.Result object at 0x105a714d0>, <py_bing_search.Result object at 0x105a71550>, <py_bing_search.Result object at 0x105a715d0>, <py_bing_search.Result object at 0x105a71650>, <py_bing_search.Result object at 0x105a716d0>, <py_bing_search.Result object at 0x105a71750>, <py_bing_search.Result object at 0x105a717d0>, <py_bing_search.Result object at 0x105a71850>, <py_bing_search.Result object at 0x105a718d0>, <py_bing_search.Result object at 0x105a71950>, <py_bing_search.Result object at 0x105a719d0>, <py_bing_search.Result object at 0x105a71a50>, <py_bing_search.Result object at 0x105a71ad0>, <py_bing_search.Result object at 0x105a71b50>, <py_bing_search.Result object at 0x105a71bd0>], "https://api.datamarket.azure.com/Data.ashx/Bing/Search/Web?Query='ol%C3%A1'&$skip=50&$top=50")

**Comment by tristantao** [comment]
Yea, it seems to work in the newest version, closing now.
